/**
 * Venue Bootstrap — check-first bootstrap + conditional repair.
 *
 * Runs once at server startup, before sync workers.
 * Checks local PG, reads schema state, verifies Neon readiness.
 */

import { existsSync } from 'fs'
import path from 'path'
import { createChildLogger } from '@/lib/logger'
import { config } from '@/lib/system-config'
import { EXPECTED_SCHEMA_VERSION, EXPECTED_SEED_VERSION, PROVISIONER_VERSION, APP_VERSION } from '@/lib/version-contract'
import { ensureSchemaStateTable, readSchemaState, writeSchemaState, markRepair } from '@/lib/venue-schema-state'
import { checkBaseSeedPresent } from '@/lib/base-seed-check'

const log = createChildLogger('venue-bootstrap')

// Core tables that must exist for a functional POS
const CORE_TABLES = [
  'Location', 'Role', 'Employee', 'Order', 'Category',
  'MenuItem', 'OrderItem', 'ModifierGroup', 'Modifier',
  'Terminal', 'Section', 'Table',
]

// Required enums
const REQUIRED_ENUMS = ['TabStatus', 'OrderStatus', 'CategoryType', 'FulfillmentType']

export interface SchemaReadiness {
  schemaVersionMatch: boolean
  schemaVersionBehind: boolean
  schemaVersionAhead: boolean
  coreTablesExist: boolean
  requiredEnumsExist: boolean
  baseSeedPresent: boolean
  schemaVersion: string | null
  seedVersion: string | null
}

export interface BootstrapResult {
  localDb: boolean
  localSchemaVersion: string | null
  neonReachable: boolean
  neonSchemaReady: SchemaReadiness | null
  neonRepaired: boolean
  seedDataPresent: boolean
  localBootOk: boolean  // local PG is up and basic Neon connectivity is ok — does NOT mean sync-safe
  syncContractReady: boolean  // matches POS sync-start gate exactly
  degradedReasons: string[]
}

let cachedResult: BootstrapResult | null = null

export function getBootstrapResult(): BootstrapResult | null {
  return cachedResult
}

async function checkCoreTablesExist(
  client: { $queryRawUnsafe: (sql: string) => Promise<unknown[]> }
): Promise<boolean> {
  for (const table of CORE_TABLES) {
    const rows = await client.$queryRawUnsafe(`
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = '${table}'
    `)
    if (rows.length === 0) return false
  }
  return true
}

async function checkEnumsExist(
  client: { $queryRawUnsafe: (sql: string) => Promise<unknown[]> }
): Promise<boolean> {
  for (const enumName of REQUIRED_ENUMS) {
    const rows = await client.$queryRawUnsafe(`
      SELECT 1 FROM pg_type WHERE typname = '${enumName}'
    `)
    if (rows.length === 0) return false
  }
  return true
}

async function countTables(
  client: { $queryRawUnsafe: (sql: string) => Promise<unknown[]> }
): Promise<number> {
  const rows = await client.$queryRawUnsafe(`
    SELECT COUNT(*)::int as count FROM information_schema.tables
    WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
  `) as Array<{ count: number }>
  return rows[0]?.count ?? 0
}

async function buildReadiness(
  client: { $queryRawUnsafe: (sql: string) => Promise<unknown[]> },
  state: { schemaVersion: string; seedVersion: string } | null
): Promise<SchemaReadiness> {
  const schemaVersion = state?.schemaVersion ?? null
  const seedVersion = state?.seedVersion ?? null
  const coreTablesExist = await checkCoreTablesExist(client)
  const requiredEnumsExist = await checkEnumsExist(client)
  const seedResult = await checkBaseSeedPresent(client)

  return {
    schemaVersionMatch: schemaVersion === EXPECTED_SCHEMA_VERSION,
    schemaVersionBehind: schemaVersion !== null && schemaVersion < EXPECTED_SCHEMA_VERSION,
    schemaVersionAhead: schemaVersion !== null && schemaVersion > EXPECTED_SCHEMA_VERSION,
    coreTablesExist,
    requiredEnumsExist,
    baseSeedPresent: seedResult.ok,
    schemaVersion,
    seedVersion,
  }
}

/**
 * Apply schema to an empty Neon DB.
 *
 * CANONICAL PATH: run numbered migrations from scripts/migrations/ via the
 * same logic as nuc-pre-migrate.js (advisory lock, tracking table, ordered
 * execution). This is the same path used by NUC boot and Vercel builds.
 *
 * FALLBACK (schema.sql): EXPLICITLY EXCEPTIONAL -- only used when:
 *   1. Standalone build without migrations directory (e.g., production Docker image)
 *   2. Target DB is completely empty (0 tables)
 *   3. NEVER for upgrades (version behind -> version current)
 *   4. NEVER for partial schema repair (some tables exist but not all)
 * If you find yourself reaching for this fallback in a new context, STOP and
 * create a proper migration instead.
 */
/**
 * Apply schema to an empty Neon DB via schema.sql (generated at build time).
 *
 * schema.sql is the complete DDL for all tables, enums, indexes, and constraints.
 * It's generated by `scripts/generate-schema-sql.mjs` during `npm run build`.
 *
 * This is used ONLY for:
 *   1. Empty Neon DBs detected during bootstrap (0 tables)
 *   2. NEVER for upgrades (version behind -> version current)
 *   3. NEVER for partial schema repair (some tables exist but not all)
 *
 * For NUC local DB schema changes, use scripts/migrations/NNN-*.js via
 * nuc-pre-migrate.js (runs during pre-start, not here).
 */
async function applySchemaToEmptyDb(
  client: {
    $executeRawUnsafe: (sql: string, ...params: unknown[]) => Promise<unknown>
    $queryRawUnsafe: (sql: string) => Promise<unknown[]>
  }
): Promise<void> {
  // Load schema SQL from best available source
  const publicPath = path.join(process.cwd(), 'public/schema.sql')
  const prismaPath = path.join(process.cwd(), 'prisma/schema.sql')
  const schemaPath = existsSync(publicPath) ? publicPath : existsSync(prismaPath) ? prismaPath : null
  if (!schemaPath) {
    throw new Error(
      'Cannot repair empty DB: neither public/schema.sql nor prisma/schema.sql found. ' +
      'These files are generated at build time by generate-schema-sql.mjs.'
    )
  }

  log.info({ source: schemaPath.includes('public') ? 'public/schema.sql' : 'prisma/schema.sql' }, 'Applying schema to empty Neon DB')
  const { readFileSync } = await import('fs')
  const sql = readFileSync(schemaPath, 'utf-8')
  await client.$executeRawUnsafe(sql)
  log.info('Schema applied successfully')
}

export async function runBootstrap(): Promise<BootstrapResult> {
  const result: BootstrapResult = {
    localDb: false,
    localSchemaVersion: null,
    neonReachable: false,
    neonSchemaReady: null,
    neonRepaired: false,
    seedDataPresent: false,
    localBootOk: false,
    syncContractReady: false,
    degradedReasons: [],
  }

  try {
    // 1. Check local PG
    const { masterClient } = await import('@/lib/db')
    try {
      await masterClient.$queryRawUnsafe('SELECT 1')
      result.localDb = true
    } catch (err) {
      log.error({ err }, 'Local PG check failed')
      cachedResult = result
      return result
    }

    // 2. Read local _venue_schema_state
    const localState = await readSchemaState(masterClient)
    result.localSchemaVersion = localState?.schemaVersion ?? null

    // 3. Check Neon if configured
    const neonUrl = process.env.NEON_DATABASE_URL
    if (neonUrl) {
      try {
        // Use PrismaPg adapter (Prisma 7 doesn't support datasourceUrl in constructor)
        const { PrismaClient } = await import('@/generated/prisma/client')
        const { PrismaPg } = await import('@prisma/adapter-pg')
        const directUrl = process.env.NEON_DIRECT_URL || neonUrl
        const neonAdapter = new PrismaPg({ connectionString: directUrl, max: 2 })
        const neonClient = new PrismaClient({ adapter: neonAdapter })

        try {
          await neonClient.$queryRawUnsafe('SELECT 1')
          result.neonReachable = true

          // Backup/standby: read-only observation only — NEVER mutate Neon
          if (config.stationRole === 'backup') {
            log.info('Station is BACKUP — Neon observation only (no mutations)')
            const neonState = await readSchemaState(neonClient)
            result.neonSchemaReady = await buildReadiness(neonClient, neonState)
            result.degradedReasons.push('backup-readonly-mode')
            // Skip all mutation paths below
          } else {
            // Primary: full check + conditional repair
            const neonState = await readSchemaState(neonClient)
            const tableCount = await countTables(neonClient)

            if (!neonState && tableCount === 0) {
              // Primary: auto-repair via schema.sql
              log.info('Neon DB is empty — running auto-repair via canonical migration path')
              try {
                await applySchemaToEmptyDb(neonClient)
                await ensureSchemaStateTable(neonClient)
                await writeSchemaState(neonClient, {
                  schemaVersion: EXPECTED_SCHEMA_VERSION,
                  seedVersion: EXPECTED_SEED_VERSION,
                  provisionerVersion: PROVISIONER_VERSION,
                  provisionedAt: new Date(),
                  provisionedBy: 'nuc-bootstrap',
                  appVersion: APP_VERSION,
                })
                await markRepair(neonClient, 'nuc-bootstrap', 'bootstrap-empty-db')
                result.neonRepaired = true
                result.neonSchemaReady = await buildReadiness(neonClient, {
                  schemaVersion: EXPECTED_SCHEMA_VERSION,
                  seedVersion: EXPECTED_SEED_VERSION,
                })
              } catch (repairErr) {
                log.error({ err: repairErr }, 'Auto-repair of empty Neon DB failed')
                result.neonSchemaReady = await buildReadiness(neonClient, null)
              }
            } else if (!neonState && tableCount > 0) {
            // Tables exist but no _venue_schema_state — likely Vercel ran prisma db push.
            // Create the state table and seed it with the NUC's expected version so sync can start.
            log.info(
              { tableCount },
              'Neon DB has tables but no _venue_schema_state — creating state table (likely Vercel-provisioned)'
            )
            try {
              await ensureSchemaStateTable(neonClient)
              await writeSchemaState(neonClient, {
                schemaVersion: EXPECTED_SCHEMA_VERSION,
                seedVersion: EXPECTED_SEED_VERSION,
                provisionerVersion: PROVISIONER_VERSION,
                provisionedAt: new Date(),
                provisionedBy: 'nuc-bootstrap-backfill',
                appVersion: APP_VERSION,
              })
              result.neonSchemaReady = await buildReadiness(neonClient, {
                schemaVersion: EXPECTED_SCHEMA_VERSION,
                seedVersion: EXPECTED_SEED_VERSION,
              })
              log.info('Created _venue_schema_state for existing Neon DB')
            } catch (backfillErr) {
              log.error({ err: backfillErr }, 'Failed to create _venue_schema_state — falling back to degraded')
              result.neonSchemaReady = await buildReadiness(neonClient, null)
            }
            } else if (neonState) {
              // State exists -- check versions
              if (neonState.schemaVersion < EXPECTED_SCHEMA_VERSION) {
                log.error(
                  { expected: EXPECTED_SCHEMA_VERSION, actual: neonState.schemaVersion },
                  'Neon schema version behind — sync will be blocked. Deploy pipeline required.'
                )
              } else if (neonState.schemaVersion > EXPECTED_SCHEMA_VERSION) {
                log.warn(
                  { expected: EXPECTED_SCHEMA_VERSION, actual: neonState.schemaVersion },
                  'Neon schema version ahead of this POS build — safe to proceed'
                )
              }
              result.neonSchemaReady = await buildReadiness(neonClient, neonState)

              // Flag degraded if too many repairs
              if (neonState.repairCount >= 3) {
                log.warn({ repairCount: neonState.repairCount, lastReason: neonState.lastRepairReason },
                  'Neon DB has been repaired 3+ times — marking as degraded')
                result.degradedReasons.push('repeated-schema-repair')
              }

              // Neon schema BEHIND local is a rollback scenario — block sync but don't kill the process
              if (neonState.schemaVersion < EXPECTED_SCHEMA_VERSION && config.isProduction) {
                log.error(
                  { expected: EXPECTED_SCHEMA_VERSION, actual: neonState.schemaVersion },
                  'Neon schema behind NUC in production — sync blocked until deploy pipeline catches up'
                )
                result.degradedReasons.push('neon-schema-behind')
              }
            }
          } // close primary else block
        } finally {
          await neonClient.$disconnect()
        }
      } catch (err) {
        log.warn({ err: err instanceof Error ? err.message : err }, 'Neon unreachable — operating in local-only mode')
        result.neonReachable = false
        result.degradedReasons.push('neon-unreachable')
      }
    }

    // 4. Check local seed
    const seedResult = await checkBaseSeedPresent(masterClient)
    result.seedDataPresent = seedResult.ok
    if (!seedResult.ok) {
      log.warn({ missing: seedResult.missing }, 'Base seed data incomplete')
      result.degradedReasons.push('seed-data-missing')
    }

    // 5. Determine overall readiness
    const neonOk = !neonUrl || (result.neonSchemaReady?.coreTablesExist ?? true)
    result.localBootOk = result.localDb && neonOk

    // syncContractReady: matches the exact contract server.ts uses for sync workers
    // Schema version: match OR ahead is OK (Vercel deployed newer schema). Only "behind" blocks sync.
    const nsr = result.neonSchemaReady
    const schemaVersionOk = !!nsr && (nsr.schemaVersionMatch || nsr.schemaVersionAhead)
    result.syncContractReady = result.localDb && !!neonUrl && result.neonReachable && !!nsr &&
      nsr.coreTablesExist && nsr.requiredEnumsExist && schemaVersionOk && nsr.baseSeedPresent

    log.info({
      localDb: result.localDb,
      localSchemaVersion: result.localSchemaVersion,
      neonReachable: result.neonReachable,
      neonRepaired: result.neonRepaired,
      neonSchemaVersion: result.neonSchemaReady?.schemaVersion ?? 'N/A',
      seedPresent: result.seedDataPresent,
      localBootOk: result.localBootOk,
    }, 'Bootstrap complete')

    cachedResult = result
    return result
  } catch (err) {
    log.error({ err }, 'Bootstrap failed with unexpected error')
    cachedResult = result
    return result
  }
}
