/**
 * Shared Sample Data for Floor Plan Test Pages
 *
 * Used by both:
 * - /test-floorplan/page.tsx (Front of House)
 * - /test-floorplan/editor/page.tsx (Editor)
 */

import type { FloorPlan, Fixture, Table } from '@/domains/floor-plan/shared/types';

// =============================================================================
// FLOOR PLANS - All rooms are 40x30 with 0.25ft grid for editor precision
// =============================================================================

export const sampleFloorPlans: FloorPlan[] = [
  {
    id: 'room-main',
    locationId: 'loc-1',
    name: 'Main Dining',
    type: 'indoor',
    widthFeet: 40,
    heightFeet: 30,
    gridSizeFeet: 0.25,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'room-bar',
    locationId: 'loc-1',
    name: 'Bar Area',
    type: 'bar',
    widthFeet: 40,
    heightFeet: 30,
    gridSizeFeet: 0.25,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'room-patio',
    locationId: 'loc-1',
    name: 'Patio',
    type: 'patio',
    widthFeet: 40,
    heightFeet: 30,
    gridSizeFeet: 0.25,
    isActive: true,
    sortOrder: 3,
  },
];

// =============================================================================
// FIXTURES - Walls and other fixed elements
// =============================================================================

export const sampleFixtures: Fixture[] = [
  // Main Dining - Boundary Walls
  {
    id: 'fix-1',
    floorPlanId: 'room-main',
    roomId: 'room-main',
    type: 'wall',
    category: 'barrier',
    label: 'North Wall',
    geometry: { type: 'line', start: { x: 0, y: 0 }, end: { x: 40, y: 0 } },
    color: '#424242',
    opacity: 1,
    thickness: 0.5,
    height: 'full',
    blocksPlacement: true,
    blocksMovement: true,
    snapTarget: false,
    isActive: true,
  },
  {
    id: 'fix-2',
    floorPlanId: 'room-main',
    roomId: 'room-main',
    type: 'wall',
    category: 'barrier',
    label: 'South Wall',
    geometry: { type: 'line', start: { x: 0, y: 30 }, end: { x: 40, y: 30 } },
    color: '#424242',
    opacity: 1,
    thickness: 0.5,
    height: 'full',
    blocksPlacement: true,
    blocksMovement: true,
    snapTarget: false,
    isActive: true,
  },
  {
    id: 'fix-3',
    floorPlanId: 'room-main',
    roomId: 'room-main',
    type: 'wall',
    category: 'barrier',
    label: 'West Wall',
    geometry: { type: 'line', start: { x: 0, y: 0 }, end: { x: 0, y: 30 } },
    color: '#424242',
    opacity: 1,
    thickness: 0.5,
    height: 'full',
    blocksPlacement: true,
    blocksMovement: true,
    snapTarget: false,
    isActive: true,
  },
  {
    id: 'fix-4',
    floorPlanId: 'room-main',
    roomId: 'room-main',
    type: 'wall',
    category: 'barrier',
    label: 'East Wall',
    geometry: { type: 'line', start: { x: 40, y: 0 }, end: { x: 40, y: 30 } },
    color: '#424242',
    opacity: 1,
    thickness: 0.5,
    height: 'full',
    blocksPlacement: true,
    blocksMovement: true,
    snapTarget: false,
    isActive: true,
  },
  // Kitchen boundary in Main Dining
  {
    id: 'fix-5',
    floorPlanId: 'room-main',
    roomId: 'room-main',
    type: 'kitchen_boundary',
    category: 'zone',
    label: 'Kitchen',
    geometry: { type: 'rectangle', position: { x: 30, y: 0 }, width: 10, height: 10, rotation: 0 },
    color: '#FFEB3B',
    opacity: 0.3,
    thickness: 0,
    height: null,
    blocksPlacement: true,
    blocksMovement: false,
    snapTarget: false,
    isActive: true,
  },
  // Bar Area - Bar Counter
  {
    id: 'fix-6',
    floorPlanId: 'room-bar',
    roomId: 'room-bar',
    type: 'bar_counter',
    category: 'surface',
    label: 'Main Bar',
    geometry: { type: 'rectangle', position: { x: 2, y: 2 }, width: 20, height: 3, rotation: 0 },
    color: '#8D6E63',
    opacity: 1,
    thickness: 0,
    height: 'counter',
    blocksPlacement: true,
    blocksMovement: true,
    snapTarget: true,
    isActive: true,
  },
  // Patio - Railing
  {
    id: 'fix-7',
    floorPlanId: 'room-patio',
    roomId: 'room-patio',
    type: 'railing',
    category: 'barrier',
    label: 'Patio Railing',
    geometry: { type: 'line', start: { x: 0, y: 25 }, end: { x: 30, y: 25 } },
    color: '#795548',
    opacity: 1,
    thickness: 0.3,
    height: 'half',
    blocksPlacement: true,
    blocksMovement: true,
    snapTarget: false,
    isActive: true,
  },
  // Pillar in Main Dining
  {
    id: 'fix-8',
    floorPlanId: 'room-main',
    roomId: 'room-main',
    type: 'pillar',
    category: 'barrier',
    label: 'Support Pillar',
    geometry: { type: 'circle', center: { x: 20, y: 15 }, radius: 1 },
    color: '#9E9E9E',
    opacity: 1,
    thickness: 0,
    height: 'full',
    blocksPlacement: true,
    blocksMovement: true,
    snapTarget: false,
    isActive: true,
  },
];

// =============================================================================
// TABLES - Sample tables for Front of House display
// =============================================================================

export const sampleTables: Table[] = [
  {
    id: 'table-1',
    locationId: 'loc-1',
    floorPlanId: 'room-main',
    sectionId: null,
    label: 'T1',
    objectType: 'dining_table',
    category: 'seatable',
    shape: 'round',
    positionX: 5,
    positionY: 8,
    width: 4,
    height: 4,
    rotation: 0,
    minCapacity: 2,
    maxCapacity: 4,
    defaultCapacity: 4,
    isActive: true,
    isReservable: true,
    sortOrder: 1,
    groupId: null,
    combinedTableIds: [],
    color: null,
    entertainmentConfig: null,
  },
  {
    id: 'table-2',
    locationId: 'loc-1',
    floorPlanId: 'room-main',
    sectionId: null,
    label: 'T2',
    objectType: 'dining_table',
    category: 'seatable',
    shape: 'square',
    positionX: 12,
    positionY: 8,
    width: 3,
    height: 3,
    rotation: 0,
    minCapacity: 2,
    maxCapacity: 4,
    defaultCapacity: 4,
    isActive: true,
    isReservable: true,
    sortOrder: 2,
    groupId: null,
    combinedTableIds: [],
    color: null,
    entertainmentConfig: null,
  },
  {
    id: 'table-3',
    locationId: 'loc-1',
    floorPlanId: 'room-main',
    sectionId: null,
    label: 'T3',
    objectType: 'dining_table',
    category: 'seatable',
    shape: 'rectangle',
    positionX: 5,
    positionY: 18,
    width: 6,
    height: 3,
    rotation: 0,
    minCapacity: 4,
    maxCapacity: 6,
    defaultCapacity: 6,
    isActive: true,
    isReservable: true,
    sortOrder: 3,
    groupId: null,
    combinedTableIds: [],
    color: null,
    entertainmentConfig: null,
  },
  {
    id: 'table-4',
    locationId: 'loc-1',
    floorPlanId: 'room-main',
    sectionId: null,
    label: 'T4',
    objectType: 'dining_table',
    category: 'seatable',
    shape: 'hexagon',
    positionX: 22,
    positionY: 8,
    width: 4,
    height: 4,
    rotation: 0,
    minCapacity: 4,
    maxCapacity: 6,
    defaultCapacity: 6,
    isActive: true,
    isReservable: true,
    sortOrder: 4,
    groupId: null,
    combinedTableIds: [],
    color: null,
    entertainmentConfig: null,
  },
  {
    id: 'table-5',
    locationId: 'loc-1',
    floorPlanId: 'room-main',
    sectionId: null,
    label: 'B1',
    objectType: 'booth',
    category: 'seatable',
    shape: 'rectangle',
    positionX: 22,
    positionY: 18,
    width: 5,
    height: 3,
    rotation: 0,
    minCapacity: 4,
    maxCapacity: 6,
    defaultCapacity: 4,
    isActive: true,
    isReservable: true,
    sortOrder: 5,
    groupId: null,
    combinedTableIds: [],
    color: '#8B4513',
    entertainmentConfig: null,
  },
  {
    id: 'pool-1',
    locationId: 'loc-1',
    floorPlanId: 'room-bar',
    sectionId: null,
    label: 'Pool 1',
    objectType: 'pool_table',
    category: 'entertainment',
    shape: 'rectangle',
    positionX: 5,
    positionY: 10,
    width: 8,
    height: 4,
    rotation: 0,
    minCapacity: 1,
    maxCapacity: 4,
    defaultCapacity: 2,
    isActive: true,
    isReservable: true,
    sortOrder: 1,
    groupId: null,
    combinedTableIds: [],
    color: '#2E7D32',
    entertainmentConfig: {
      hourlyRate: 15,
      minimumMinutes: 30,
      overtimeMultiplier: 1.5,
      requiresDeposit: false,
      depositAmount: 0,
    },
  },
  {
    id: 'dart-1',
    locationId: 'loc-1',
    floorPlanId: 'room-bar',
    sectionId: null,
    label: 'Darts',
    objectType: 'dart_board',
    category: 'entertainment',
    shape: 'square',
    positionX: 18,
    positionY: 10,
    width: 3,
    height: 3,
    rotation: 0,
    minCapacity: 1,
    maxCapacity: 4,
    defaultCapacity: 2,
    isActive: true,
    isReservable: true,
    sortOrder: 2,
    groupId: null,
    combinedTableIds: [],
    color: null,
    entertainmentConfig: {
      hourlyRate: 10,
      minimumMinutes: 30,
      overtimeMultiplier: 1.5,
      requiresDeposit: false,
      depositAmount: 0,
    },
  },
  {
    id: 'patio-1',
    locationId: 'loc-1',
    floorPlanId: 'room-patio',
    sectionId: null,
    label: 'P1',
    objectType: 'dining_table',
    category: 'seatable',
    shape: 'round',
    positionX: 5,
    positionY: 8,
    width: 4,
    height: 4,
    rotation: 0,
    minCapacity: 2,
    maxCapacity: 4,
    defaultCapacity: 4,
    isActive: true,
    isReservable: true,
    sortOrder: 1,
    groupId: null,
    combinedTableIds: [],
    color: null,
    entertainmentConfig: null,
  },
  {
    id: 'patio-2',
    locationId: 'loc-1',
    floorPlanId: 'room-patio',
    sectionId: null,
    label: 'P2',
    objectType: 'dining_table',
    category: 'seatable',
    shape: 'round',
    positionX: 15,
    positionY: 8,
    width: 4,
    height: 4,
    rotation: 0,
    minCapacity: 2,
    maxCapacity: 4,
    defaultCapacity: 4,
    isActive: true,
    isReservable: true,
    sortOrder: 2,
    groupId: null,
    combinedTableIds: [],
    color: null,
    entertainmentConfig: null,
  },
];
