#!/usr/bin/env bash
# =============================================================================
# 03-secrets.sh — Generate/load all secrets, write .env file
# =============================================================================
# Entry: run_secrets
# Expects: STATION_ROLE, ALREADY_REGISTERED, SERVER_NODE_ID, SERVER_API_KEY,
#          HARDWARE_FINGERPRINT, MC_URL, LOCATION_ID, MC_LOCATION_ID,
#          CLOUD_ORGANIZATION_ID, CLOUD_ENTERPRISE_ID, BACKOFFICE_API_URL,
#          DATABASE_URL, DIRECT_URL, NEON_DATABASE_URL, NEON_DIRECT_URL,
#          SYNC_ENABLED, SERVER_URL, VIRTUAL_IP, PRIMARY_NUC_IP, VENUE_SLUG,
#          APP_BASE, ENV_FILE, KEY_DIR, POSUSER, GIT_REPO
# Sets: USE_LOCAL_PG (may update), DATABASE_URL, DIRECT_URL, GIT_REPO,
#       NEON_DATABASE_URL, NEON_DIRECT_URL, SYNC_ENABLED
# =============================================================================

run_secrets() {
  local _start=$(date +%s)
  log "Stage: secrets — starting"

  if [[ "$ALREADY_REGISTERED" == "false" ]] && [[ "$STATION_ROLE" == "server" || "$STATION_ROLE" == "backup" ]]; then
    # ── Write environment file (DEPLOY_TOKEN is never stored here — goes to .git-credentials only) ──
    mkdir -p "$APP_BASE"
    INTERNAL_SECRET=$(openssl rand -hex 32)
    CELLULAR_SECRET=$(openssl rand -hex 32)
    SESSION_SECRET=$(openssl rand -hex 32)
    TENANT_SIGNING_KEY=$(openssl rand -hex 32)

    # Build HA section for .env (server or backup)
    HA_ENV_SECTION=""
    if [[ -n "${VIRTUAL_IP:-}" ]]; then
      HA_ENV_SECTION="
# High Availability
VIRTUAL_IP=${VIRTUAL_IP}"
      if [[ -n "${PRIMARY_NUC_IP:-}" ]]; then
        HA_ENV_SECTION="${HA_ENV_SECTION}
PRIMARY_NUC_IP=${PRIMARY_NUC_IP}"
      fi
    fi

    cat > "$ENV_FILE" <<ENVEOF
# Generated by installer.run — $(date -u +%Y-%m-%dT%H:%M:%SZ)
STATION_ROLE=${STATION_ROLE}

# Mission Control
SERVER_NODE_ID=${SERVER_NODE_ID}
SERVER_API_KEY=${SERVER_API_KEY}
HARDWARE_FINGERPRINT=${HARDWARE_FINGERPRINT}
MISSION_CONTROL_URL=${MC_URL}
LOCATION_ID=${LOCATION_ID}
CLOUD_LOCATION_ID=${MC_LOCATION_ID}
CLOUD_ORGANIZATION_ID=${CLOUD_ORGANIZATION_ID}
CLOUD_ENTERPRISE_ID=${CLOUD_ENTERPRISE_ID}

# Cloud Backoffice (NUC -> Cloud event pipeline)
BACKOFFICE_API_URL=${BACKOFFICE_API_URL}

# Database (local PostgreSQL — primary)
DATABASE_URL=${DATABASE_URL}
DIRECT_URL=${DIRECT_URL}

# Cloud sync + cellular ingress (Neon — canonical cloud DB)
# Serves as: background sync target for upstream/downstream replication,
# AND direct write target for cellular terminals operating off-LAN.
# See docs/architecture/AUTHORITY-MODEL.md Section 7: Dual-Ingress Model.
NEON_DATABASE_URL=${NEON_DATABASE_URL}
NEON_DIRECT_URL=${NEON_DIRECT_URL}
SYNC_ENABLED=${SYNC_ENABLED:-false}

# App Configuration
NODE_ENV=production
NEXT_PUBLIC_EVENT_PROVIDER=socket
PORT=3005
INTERNAL_API_SECRET=${INTERNAL_SECRET}
CELLULAR_TOKEN_SECRET=${CELLULAR_SECRET}
SESSION_SECRET=${SESSION_SECRET}
TENANT_SIGNING_KEY=${TENANT_SIGNING_KEY}
SERVER_URL=${SERVER_URL}${HA_ENV_SECTION}
ENVEOF

    # Append POS_VENUE_SLUG only if MC returned a slug (avoids writing empty value)
    if [[ -n "${VENUE_SLUG:-}" ]]; then
      echo "" >> "$ENV_FILE"
      echo "# Venue identity (routing header for cloud relay)" >> "$ENV_FILE"
      echo "POS_VENUE_SLUG=${VENUE_SLUG}" >> "$ENV_FILE"
    fi

    # Append LOCATION_NAME if available from registration (used by RealVNC + desktop launcher)
    if [[ -n "${LOCATION_NAME:-}" ]]; then
      echo "" >> "$ENV_FILE"
      echo "# Venue display name (from MC registration, used for RealVNC + desktop)" >> "$ENV_FILE"
      echo "LOCATION_NAME=${LOCATION_NAME}" >> "$ENV_FILE"
    fi

    # .env readable by POSUSER (for app) but owned by root (contains secrets)
    chown root:"$POSUSER" "$ENV_FILE" && chmod 640 "$ENV_FILE"
    log "Environment written to $ENV_FILE"

  elif [[ "$ALREADY_REGISTERED" == "false" ]] && [[ "$STATION_ROLE" == "terminal" ]]; then
    # Fresh terminal install — write canonical terminal .env
    mkdir -p "$APP_BASE"
    cat > "$ENV_FILE" <<ENVEOF
# Generated by installer.run — $(date -u +%Y-%m-%dT%H:%M:%SZ)
STATION_ROLE=terminal
SERVER_URL=${SERVER_URL}
NODE_ENV=production
PORT=3005
ENVEOF

    # .env readable by POSUSER (for app) but owned by root (contains secrets)
    chown root:"$POSUSER" "$ENV_FILE" && chmod 640 "$ENV_FILE"
    log "Terminal environment written to $ENV_FILE"

  else
    # Already registered — load values from existing .env (both server + terminal re-runs)
    log "Using existing registration from $ENV_FILE"
    while IFS= read -r line; do
      # Skip blank lines and lines starting with #
      [[ -z "$line" ]] && continue
      [[ "$line" =~ ^[[:space:]]*# ]] && continue
      # Strip leading whitespace only (preserve # in values like DB passwords)
      line="${line#"${line%%[![:space:]]*}"}"
      [[ -z "$line" ]] && continue
      key="${line%%=*}"; val="${line#*=}"
      case "$key" in
        STATION_ROLE) PREV_ROLE="$val" ;;
        DATABASE_URL) DATABASE_URL="$val" ;;
        DIRECT_URL)   DIRECT_URL="$val" ;;
        HARDWARE_FINGERPRINT) HARDWARE_FINGERPRINT="$val" ;;
        SERVER_URL)   [[ -z "$SERVER_URL" ]] && SERVER_URL="$val" ;;
        PRIMARY_NUC_IP) [[ -z "$PRIMARY_NUC_IP" ]] && PRIMARY_NUC_IP="$val" ;;
        VIRTUAL_IP)   [[ -z "$VIRTUAL_IP" ]] && VIRTUAL_IP="$val" ;;
        LOCATION_NAME) [[ -z "${LOCATION_NAME:-}" ]] && LOCATION_NAME="$val" && VENUE_NAME="$val" ;;
        REALVNC_CLOUD_TOKEN) REALVNC_CLOUD_TOKEN="$val" ;;
      esac
    done < "$ENV_FILE"

    # Ensure backoffice URL is present (added in later installer versions)
    if ! grep -q "^BACKOFFICE_API_URL=" "$ENV_FILE" 2>/dev/null; then
      echo "" >> "$ENV_FILE"
      echo "# Cloud Backoffice (NUC -> Cloud event pipeline)" >> "$ENV_FILE"
      echo "BACKOFFICE_API_URL=$BACKOFFICE_API_URL" >> "$ENV_FILE"
      log "Added BACKOFFICE_API_URL to existing .env"
    fi

    # Ensure internal API secret is present (added in later installer versions)
    if ! grep -q "^INTERNAL_API_SECRET=" "$ENV_FILE" 2>/dev/null; then
      echo "INTERNAL_API_SECRET=$(openssl rand -hex 32)" >> "$ENV_FILE"
      log "Added INTERNAL_API_SECRET to existing .env"
    fi

    # Ensure cellular token secret is present (for cellular device JWT issuance)
    if ! grep -q "^CELLULAR_TOKEN_SECRET=" "$ENV_FILE" 2>/dev/null; then
      echo "CELLULAR_TOKEN_SECRET=$(openssl rand -hex 32)" >> "$ENV_FILE"
      log "Added CELLULAR_TOKEN_SECRET to existing .env"
    fi

    # Ensure session secret is present (for POS httpOnly session cookies)
    if ! grep -q "^SESSION_SECRET=" "$ENV_FILE" 2>/dev/null; then
      echo "SESSION_SECRET=$(openssl rand -hex 32)" >> "$ENV_FILE"
      log "Added SESSION_SECRET to existing .env"
    fi

    # Ensure tenant signing key is present (for proxy JWT signing)
    if ! grep -q "^TENANT_SIGNING_KEY=" "$ENV_FILE" 2>/dev/null; then
      echo "TENANT_SIGNING_KEY=$(openssl rand -hex 32)" >> "$ENV_FILE"
      log "Added TENANT_SIGNING_KEY to existing .env"
    fi

    # Ensure SERVER_URL is persisted (added in later installer versions)
    if [[ -n "$SERVER_URL" ]] && ! grep -q "^SERVER_URL=" "$ENV_FILE" 2>/dev/null; then
      echo "SERVER_URL=$SERVER_URL" >> "$ENV_FILE"
      log "Added SERVER_URL to existing .env"
    fi

    # Ensure GIT_REPO is set (not provided during re-run since registration is skipped)
    if [[ -z "$GIT_REPO" ]]; then
      GIT_REPO="https://github.com/GetwithitMan/gwi-pos.git"
      log "Using default Git repo URL (existing registration)."
    fi

    # Load existing sync vars from .env (may have been set by a previous install)
    while IFS= read -r line; do
      [[ -z "$line" ]] && continue
      [[ "$line" =~ ^[[:space:]]*# ]] && continue
      line="${line#"${line%%[![:space:]]*}"}"
      key="${line%%=*}"; val="${line#*=}"
      case "$key" in
        NEON_DATABASE_URL) NEON_DATABASE_URL="$val" ;;
        NEON_DIRECT_URL)   NEON_DIRECT_URL="$val" ;;
        SYNC_ENABLED)      SYNC_ENABLED="$val" ;;
      esac
    done < "$ENV_FILE"
    SYNC_ENABLED="${SYNC_ENABLED:-false}"
    NEON_DATABASE_URL="${NEON_DATABASE_URL:-}"
    NEON_DIRECT_URL="${NEON_DIRECT_URL:-}"

    # ── Offline-first fix: if DATABASE_URL points at Neon/cloud, redirect to local PG ──
    # Older installers set DATABASE_URL to Neon — this breaks offline-first architecture.
    # Move cloud URL to NEON_DATABASE_URL (sync + cellular ingress) and force local PG.
    if [[ -n "$DATABASE_URL" ]] && [[ "$DATABASE_URL" != *"localhost"* ]] && [[ "$DATABASE_URL" != *"127.0.0.1"* ]]; then
      # Always update NEON_DATABASE_URL from the cloud DATABASE_URL, even if
      # NEON_DATABASE_URL already has a value (which may be stale from a prior install).
      NEON_DATABASE_URL="$DATABASE_URL"
      NEON_DIRECT_URL="${DIRECT_URL:-}"
      SYNC_ENABLED="true"
      log "Migrating cloud DATABASE_URL -> NEON_DATABASE_URL (offline-first fix)"
      DATABASE_URL=""
      DIRECT_URL=""
      log "Cleared cloud DATABASE_URL — local PostgreSQL will be primary"
      # Rewrite .env to persist the fix (so future re-runs don't hit the same issue)
      sed -i '/^DATABASE_URL=/d' "$ENV_FILE"
      sed -i '/^DIRECT_URL=/d' "$ENV_FILE"
      # Always update NEON_DATABASE_URL (handles both fresh writes and stale overwrites)
      if grep -q "^NEON_DATABASE_URL=" "$ENV_FILE" 2>/dev/null; then
        sed -i "s|^NEON_DATABASE_URL=.*|NEON_DATABASE_URL=$NEON_DATABASE_URL|" "$ENV_FILE"
        sed -i "s|^NEON_DIRECT_URL=.*|NEON_DIRECT_URL=$NEON_DIRECT_URL|" "$ENV_FILE"
        sed -i "s|^SYNC_ENABLED=.*|SYNC_ENABLED=$SYNC_ENABLED|" "$ENV_FILE"
      else
        echo "" >> "$ENV_FILE"
        echo "# Neon cloud sync (offline-first — local PG is primary)" >> "$ENV_FILE"
        echo "NEON_DATABASE_URL=$NEON_DATABASE_URL" >> "$ENV_FILE"
        echo "NEON_DIRECT_URL=$NEON_DIRECT_URL" >> "$ENV_FILE"
        echo "SYNC_ENABLED=$SYNC_ENABLED" >> "$ENV_FILE"
      fi
    fi

    # Fix: strip surrounding double-quotes from .env values (older installers wrote PORT="3005" etc)
    # systemd EnvironmentFile treats quotes as literal — PORT="3005" -> Node gets "3005" -> NaN
    # Only strip quotes that wrap the entire value (KEY="value" -> KEY=value), not mid-value quotes
    if grep -qE '^[A-Z_]+=".+"$' "$ENV_FILE" 2>/dev/null; then
      sed -i '/^[A-Z_]*=".*"$/s/="\([^"]*\)"/=\1/' "$ENV_FILE"
      log "Stripped legacy double-quotes from .env values"
    fi

    # Determine local PG — after offline-first redirect, DATABASE_URL should be empty or local
    if [[ -z "$DATABASE_URL" ]] || [[ "$DATABASE_URL" == *"localhost"* ]] || [[ "$DATABASE_URL" == *"127.0.0.1"* ]]; then
      USE_LOCAL_PG=true
    fi

    # Canonicalize terminal .env on re-runs (normalize values, not just add missing)
    if [[ "$STATION_ROLE" == "terminal" ]]; then
      # Remove and re-add canonical values (fixes wrong values from manual edits or old installers)
      sed -i '/^NODE_ENV=/d; /^PORT=/d; /^STATION_ROLE=/d' "$ENV_FILE" 2>/dev/null || true
      {
        echo "STATION_ROLE=terminal"
        echo "NODE_ENV=production"
        echo "PORT=3005"
      } >> "$ENV_FILE"
      # Ensure SERVER_URL is correct (may have changed)
      if [[ -n "$SERVER_URL" ]]; then
        sed -i '/^SERVER_URL=/d' "$ENV_FILE" 2>/dev/null || true
        echo "SERVER_URL=$SERVER_URL" >> "$ENV_FILE"
      fi
      # Scrub any stale server-only keys (from prior role switch or manual copy)
      sed -i '/^SERVER_NODE_ID=/d; /^SERVER_API_KEY=/d; /^HARDWARE_FINGERPRINT=/d' "$ENV_FILE" 2>/dev/null || true
      sed -i '/^MISSION_CONTROL_URL=/d; /^LOCATION_ID=/d; /^CLOUD_LOCATION_ID=/d' "$ENV_FILE" 2>/dev/null || true
      sed -i '/^CLOUD_ORGANIZATION_ID=/d; /^CLOUD_ENTERPRISE_ID=/d' "$ENV_FILE" 2>/dev/null || true
      sed -i '/^DATABASE_URL=/d; /^DIRECT_URL=/d; /^NEON_DATABASE_URL=/d; /^NEON_DIRECT_URL=/d' "$ENV_FILE" 2>/dev/null || true
      sed -i '/^SYNC_ENABLED=/d; /^BACKOFFICE_API_URL=/d; /^INTERNAL_API_SECRET=/d' "$ENV_FILE" 2>/dev/null || true
      sed -i '/^NEXT_PUBLIC_EVENT_PROVIDER=/d' "$ENV_FILE" 2>/dev/null || true
      log "Canonicalized terminal .env (STATION_ROLE, NODE_ENV, PORT, SERVER_URL) + scrubbed server-only keys"
    fi

    # Canonicalize server .env on re-runs (fix PORT, NODE_ENV, and stale branding from old installers)
    if [[ "$STATION_ROLE" == "server" ]]; then
      sed -i '/^PORT=/d; /^NODE_ENV=/d; /^STATION_ROLE=/d; /^DB_NAME=/d; /^DB_USER=/d' "$ENV_FILE" 2>/dev/null || true
      {
        echo "STATION_ROLE=server"
        echo "NODE_ENV=production"
        echo "PORT=3005"
        echo "DB_NAME=thepasspos"
        echo "DB_USER=thepasspos"
      } >> "$ENV_FILE"
      # Ensure VIRTUAL_IP is persisted if provided on re-run
      if [[ -n "${VIRTUAL_IP:-}" ]]; then
        sed -i '/^VIRTUAL_IP=/d' "$ENV_FILE" 2>/dev/null || true
        echo "VIRTUAL_IP=$VIRTUAL_IP" >> "$ENV_FILE"
      fi
      log "Canonicalized server .env (STATION_ROLE, NODE_ENV, PORT=3005, DB_NAME=thepasspos)"
    fi

    # Canonicalize backup .env on re-runs
    if [[ "$STATION_ROLE" == "backup" ]]; then
      sed -i '/^PORT=/d; /^NODE_ENV=/d; /^STATION_ROLE=/d; /^DB_NAME=/d; /^DB_USER=/d' "$ENV_FILE" 2>/dev/null || true
      {
        echo "STATION_ROLE=backup"
        echo "NODE_ENV=production"
        echo "PORT=3005"
        echo "DB_NAME=thepasspos"
        echo "DB_USER=thepasspos"
      } >> "$ENV_FILE"
      # Ensure HA vars are persisted
      if [[ -n "${VIRTUAL_IP:-}" ]]; then
        sed -i '/^VIRTUAL_IP=/d' "$ENV_FILE" 2>/dev/null || true
        echo "VIRTUAL_IP=$VIRTUAL_IP" >> "$ENV_FILE"
      fi
      if [[ -n "${PRIMARY_NUC_IP:-}" ]]; then
        sed -i '/^PRIMARY_NUC_IP=/d' "$ENV_FILE" 2>/dev/null || true
        echo "PRIMARY_NUC_IP=$PRIMARY_NUC_IP" >> "$ENV_FILE"
      fi
      log "Canonicalized backup .env (STATION_ROLE=backup, NODE_ENV, PORT=3005, DB_NAME=thepasspos)"
    fi
  fi

  log "Stage: secrets — completed in $(( $(date +%s) - _start ))s"
  return 0
}
