#!/usr/bin/env bash
# deploy-tools/build.sh — Build the deploy-tools artifact
#
# Produces a self-contained artifact with:
#   - Migration runner (pg-only, no Prisma)
#   - All migration files (copied from scripts/migrations/)
#   - migration-helpers.js (copied from scripts/)
#   - schema.sql (copied from prisma/)
#   - pg as sole runtime dependency
#
# Called from vercel-build.js or standalone for testing.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DT_DIR="$REPO_DIR/deploy-tools"
STAGING=$(mktemp -d)
ARTIFACTS_DIR="$REPO_DIR/public/artifacts"

VERSION=$(node -e "console.log(require('$REPO_DIR/package.json').version)")
GIT_SHA=$(git -C "$REPO_DIR" rev-parse --short HEAD 2>/dev/null || echo "unknown")
RELEASE_ID="${VERSION}-${GIT_SHA}"

echo "==> Building deploy-tools artifact (${RELEASE_ID})..."

# 1. Copy source files
echo "    Copying source files..."
mkdir -p "$STAGING/src"
cp "$DT_DIR/src/migrate.js" "$STAGING/src/"
cp "$DT_DIR/src/pg-compat.js" "$STAGING/src/"
cp "$DT_DIR/src/apply-schema.js" "$STAGING/src/"

# 2. Copy migration-helpers.js to artifact root
#    Migrations use require('../migration-helpers') — this path resolves
#    from migrations/xxx.js to the artifact root.
echo "    Copying migration-helpers.js..."
cp "$REPO_DIR/scripts/migration-helpers.js" "$STAGING/migration-helpers.js"

# 3. Copy all migration files (already CJS .js — no compilation needed)
echo "    Copying migrations..."
mkdir -p "$STAGING/migrations"
MIGRATION_COUNT=$(ls "$REPO_DIR/scripts/migrations/"*.js 2>/dev/null | wc -l | tr -d ' ')
cp "$REPO_DIR/scripts/migrations/"*.js "$STAGING/migrations/"
echo "    ${MIGRATION_COUNT} migration files"

# 4. Copy schema.sql (generated by generate-schema-sql.mjs during Vercel build)
if [ -f "$REPO_DIR/prisma/schema.sql" ]; then
    cp "$REPO_DIR/prisma/schema.sql" "$STAGING/schema.sql"
    SCHEMA_LINES=$(wc -l < "$STAGING/schema.sql" | tr -d ' ')
    echo "    schema.sql: ${SCHEMA_LINES} lines"
else
    echo "    WARNING: prisma/schema.sql not found — apply-schema.js will fail at runtime"
    SCHEMA_LINES=0
fi

# 5. Install pg (sole runtime dependency)
PG_VERSION=$(node -e "console.log(require('$REPO_DIR/node_modules/pg/package.json').version)" 2>/dev/null || echo "8.20.0")
echo "    Installing pg@${PG_VERSION}..."
cat > "$STAGING/package.json" << PKGJSON
{
  "name": "gwi-pos-deploy-tools",
  "version": "${VERSION}",
  "private": true,
  "dependencies": {
    "pg": "${PG_VERSION}"
  }
}
PKGJSON
(cd "$STAGING" && npm install --no-audit --no-fund --omit=dev 2>&1 | tail -3)

# 6. Validate: run validate-only mode from staged artifact
echo "    Validating staged artifact..."
VALIDATE_OUTPUT=$(DEPLOY_TOOLS_VALIDATE_ONLY=1 node "$STAGING/src/migrate.js" 2>&1) || {
    echo "FATAL: deploy-tools validate-only failed from staged artifact:" >&2
    echo "$VALIDATE_OUTPUT" >&2
    rm -rf "$STAGING"
    exit 1
}
echo "$VALIDATE_OUTPUT" | grep "\[deploy-tools" | sed 's/^/      /'

# 7. Generate metadata
cat > "$STAGING/deploy-tools-metadata.json" << METAJSON
{
  "version": "${VERSION}",
  "releaseId": "${RELEASE_ID}",
  "gitSha": "${GIT_SHA}",
  "buildDate": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "migrationCount": ${MIGRATION_COUNT},
  "schemaLines": ${SCHEMA_LINES}
}
METAJSON

# 8. Compute checksums
echo "    Computing checksums..."
(cd "$STAGING" && find . -type f \
  ! -name checksums.txt \
  ! -name deploy-tools-metadata.json \
  ! -path '*/node_modules/*' \
  -print0 | sort -z | xargs -0 shasum -a 256) > "$STAGING/checksums.txt"

# 9. Compress
mkdir -p "$ARTIFACTS_DIR"
DT_FILENAME="deploy-tools-${RELEASE_ID}.tar.gz"
DT_PATH="$ARTIFACTS_DIR/$DT_FILENAME"
if command -v zstd &>/dev/null; then
    DT_FILENAME="deploy-tools-${RELEASE_ID}.tar.zst"
    DT_PATH="$ARTIFACTS_DIR/$DT_FILENAME"
    COPYFILE_DISABLE=1 tar cf - -C "$STAGING" . | zstd -19 -T0 -o "$DT_PATH"
else
    COPYFILE_DISABLE=1 tar czf "$DT_PATH" -C "$STAGING" .
fi

DT_SIZE=$(wc -c < "$DT_PATH" | tr -d ' ')
DT_SHA256=$(shasum -a 256 "$DT_PATH" | cut -d' ' -f1)

# 10. Second validation: extract the built artifact and re-validate
echo "    Re-validating from extracted artifact..."
EXTRACT_DIR=$(mktemp -d)
if [[ "$DT_FILENAME" == *.zst ]]; then
    zstd -d "$DT_PATH" --stdout | tar xf - -C "$EXTRACT_DIR"
else
    tar xzf "$DT_PATH" -C "$EXTRACT_DIR"
fi
REVALIDATE=$(DEPLOY_TOOLS_VALIDATE_ONLY=1 node "$EXTRACT_DIR/src/migrate.js" 2>&1) || {
    echo "FATAL: deploy-tools validate-only failed from extracted artifact:" >&2
    echo "$REVALIDATE" >&2
    rm -rf "$STAGING" "$EXTRACT_DIR"
    exit 1
}
rm -rf "$EXTRACT_DIR"

echo "==> Deploy-tools artifact built: $DT_FILENAME ($(du -h "$DT_PATH" | cut -f1), sha256: ${DT_SHA256:0:16}...)"

# Clean up
rm -rf "$STAGING"
